name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Save date
      run: DATE=$(date +%Y-%m-%d-'T'-%H-%M-%S)
    - name: Build image
      run: docker build . --file Dockerfile --tag ghcr.io/jarppe/netspect:latest
    - name: Push image
      run: docker push ghcr.io/jarppe/netspect:latest
    - name: Tag with date
      run: docker tag ghcr.io/jarppe/netspect:latest ghcr.io/jarppe/netspect:$DATE
    - name: Push dated
      run: docker push ghcr.io/jarppe/netspect:$DATE
