name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        load: true
        tags: ghcr.io/jarppe/netspect:latest
    - name: Inspect
      run: docker image inspect ghcr.io/jarppe/netspect:latest
  
