name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Save the day
      run: DATE=$(date +%Y-%m-%d-'T'-%H-%M-%S)
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/jarppe/netspect:latest,ghcr.io/jarppe/netspect:${DATE}
